#!/bin/bash
#
#  status of simplant on mnrva
#
#


if [[ "" = `ps -x | grep java[^*]*simplant | awk '{print($1)}'` ]]; then
  echo "SimPlant is not running."
  exit 1
else
  echo "SimPlant is running."
  exit 0
fi